version: '3.8'

services:
  fastapi-service:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 